import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import  Navbar  from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DroidX-UI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/x-icon" href="/ss/logo.svg" />
      </head>
      <body className={inter.className}>
      <Navbar />
        <main>
            {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
